#! /bin/sh

xrandr --output LVDS1 --brightness 0.45 &
pgrep -x sxhkd > /dev/null || sxhkd &
/home/venu/.config/polybar/launch.sh &
xrdb -load $HOME/.config/.Xresources &
feh --randomize --bg-fill /usr/share/backgrounds/*
dunst &
picom --config $HOME/.config/picom.conf &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          7
bsp config presel_feedback_color "#ffffff"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 28

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^1' state=floating focus=on

bspc config focused_border_color "#2e3440"
bspc config normal_border_color "#2e3440"
